### ISSUE TITLE
Change the battery charge values of the energy levels

### ISSUE THREAD

**Issue by mgm8** [floripasat/eps#12]
To avoid unstable behaviors in the satellite when the battery charge reaches low levels, the lowest energy level must be transferred to 60 or 70 % of the battery charge. The higher levels must be increased proportionally as well.

**Comment by ramonborba** [comment]
Issue resolved

**Comment by mgm8** [comment]
@ramonborba can you link here the related commits?

**Comment by ramonborba** [comment]
aa3627cb7e9a441142dc616dd05a6d6b36579afc

**Comment by ramonborba** [comment]
Finished the final adjustments
