### ISSUE TITLE
Increase the battery charge value after a "Reset Charge" command

### ISSUE THREAD

**Issue by mgm8** [floripasat/eps#15]
Now, when the EPS module receives a "Reset Charge" command, the read battery charge goes to 0 Ah. This is a dangerous behavior, because with zero as battery charge, the satellite energy level goes to the minimum value and the OBDH module is turn off. In this scenario, we lost the satellite uplink until the battery charge goes to a higher level.

To solve this problem, the default battery charge must be a value compatible with a energy level that does not shutdown the OBDH module (2 Ah looks like a good number).

**Comment by ramonborba** [comment]
Issue resolved
