### ISSUE TITLE
Improve how to reset the battery charge in the battery monitor

### ISSUE THREAD

**Issue by mgm8** [floripasat/eps#16]
**Is your feature request related to a problem? Please describe.**
When the satellite is turned off and there is a change in the battery charge (a charging process or a natural decrease of charge), the battery monitor cannot account the change in the battery charge. This situation can lead to a de-synchronization between the battery monitor charge value and the real battery charge.

**Describe the solution you'd like**
A flag to reset the battery charge to the maximum possible value (full charge). When this flag is set, the charge value in the battery monitor must be defined as the maximum possible value (a full charged battery). When this flag is cleared, nothing happens and the battery monitor can account the battery charge variation accordingly to the satellite energy variation.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ramonborba** [comment]
Issue resolved
