### ISSUE TITLE
Improve how to define the battery charge capability

### ISSUE THREAD

**Issue by mgm8** [floripasat/eps#17]
**Is your feature request related to a problem? Please describe.**
Now, when the batteries are changed to a different model, with a different charge capacity, it's hard to define the new maximum battery charge.

**Describe the solution you'd like**
An easy way to define the battery capacity, maybe a ```#define``` directive in a header file (maybe a ```config.h``` file) defining the maximum charge in Ah.

**Describe alternatives you've considered**
None.

**Additional context**
This issue is related to #16.

**Comment by mgm8** [comment]
68534e2e5b88b88891e824ac72928418bf440684

**Comment by mgm8** [comment]
abc2fe86fe7fa0c70ceede85aef48047ec82eaae

**Comment by ramonborba** [comment]
Issue resolved
